# Generated by Django 3.2.12 on 2022-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('details', models.TextField()),
                ('saveDate', models.DateField(auto_now=True)),
                ('sudoCode', models.FileField(upload_to='file')),
                ('funCall', models.FileField(upload_to='file')),
                ('input1', models.FileField(upload_to='file')),
                ('input2', models.FileField(upload_to='file')),
                ('input3', models.FileField(upload_to='file')),
                ('output1', models.FileField(upload_to='file')),
                ('output2', models.FileField(upload_to='file')),
                ('output3', models.FileField(upload_to='file')),
            ],
        ),
    ]
